### ISSUE TITLE
spellcrafting is bugged

### ISSUE THREAD

**Issue by PeterV1982** [Dawn-of-Light/DOLSharp#253] opened 2020-09-20 19:23 UTC
when i try to combine items it says my skill isn't high enough my wuzzy has 1020 skill

**Comment by tegstewart** [comment] 2020-09-20 20:02
Which specific items are you trying to combine?

**Comment by PeterV1982** [comment] 2020-09-20 20:03
i've tried it with 3 sigil armors and 2 dragonsworn weapons. and just random things i wanted for my template, some overcharging but when i press craft it already says i don't have the skill for it

**Comment by PeterV1982** [comment] 2020-09-20 20:05
one example is:
Sigil Stiched Cloth robe
flawless fiery essence
flawless vapor essence
polished dusty shielding
flawed fiery shielding

**Comment by tegstewart** [comment] 2020-09-20 20:27
That should only happen when the total number of imbue points is higher than skill / 20.

From the Eve DB, it looks like flawless stat jewels give +25 to a stat.  Each of those contributes 17 imbue points.
The shielding jewels add 9 and 5 resist and contribute 16 and 8 imbue points respectively.

So the total is 58 imbue points, which would require 1160 spellcrafting skill.

Do those bonuses match what you're expecting?  I'm wondering if the jewel values in the DB were increased but the code wasn't updated to match.

**Comment by PeterV1982** [comment] 2020-09-20 20:29
yes it matches
however it already says it when i press crafting
and i did combines like this with this one before

**Comment by PeterV1982** [comment] 2020-09-20 20:36
and from kort it says 34.5/32 imbue points

**Comment by tegstewart** [comment] 2020-09-20 20:55
I just punched it into Kort myself and it gave me 37.5/32 imbue points, but that should still only require 750 skill.

It looks like Kort is halving the imbue point costs.  Only the highest +skill or +stat imbue cost is paid in full, and any later ones have their imbue costs halved.  The code doesn't do that, so I'll have to do some digging to find out if the formula changed at some point.

The code also only looks at imbue points as integers, so if anything it should have lower skill restrictions as it's trimming decimal imbue costs.

**Comment by PeterV1982** [comment] 2020-09-20 21:08
ok. Thanks in advance can't wait to get my tic up and running :)

**Comment by tegstewart** [comment] 2020-09-20 21:18
It's confirmed here that only the highest imbue cost gem is applied at full points cost and the rest are halved.

http://www.sarouk.net/daoc/spellcrafting.html

**Comment by tegstewart** [comment] 2020-09-21 03:25
There was an issue making it difficult to imbue an item, but now that I've got that working I tried the exact imbue you're describing, and it worked properly.  The imbue calculation rounds down, so it's actually easier than on live.

What version of the server are you running?

**Comment by Graveen** [comment] 2020-09-21 07:54
Should be fixed with latest PR

**Closed by Graveen** 2020-09-21 07:54 UTC

**Comment by PeterV1982** [comment] 2020-09-21 18:18
i just play on DOL :)
